<table border="1" width="100%">
	<tr>
		<th>
			<br>
			<center>
				{attacker}
				<br>
				{weapon}: {attacker_weapon}% {shield}: {attacker_shield}% {hull_plating}: {attacker_hull_plating}%
				<table border="1">
					<tr>
						<th>
							{shipType}
						</th>
						{attacker_names}
					</tr>
					<tr>
						<th>
							{shipCount}
						</th>
						{attacker_counts}
					</tr>
					<tr>
						<th>
							{weapon}
						</th>
						{attacker_weapons}
					</tr>
					<tr>
						<th>
							{shield}
						</th>
						{attacker_shields}
					</tr>
					<tr>
						<th>
							{hull_plating}
						</th>
						{attacker_hull_platings}
					</tr>
				</table>
			</center>
		</th>
	</tr>
</table>
<table border="1" width="100%">
	<tr>
		<th>
			<br>
			<center>
				{defender}
				<br>
				{weapon}: {defender_weapon}% {shield}: {defender_shield}% {hull_plating}: {defender_hull_plating}%
				<table border="1">
					<tr>
						<th>
							{shipType}
						</th>
						{defender_names}
					</tr>
					<tr>
						<th>
							{shipCount}
						</th>
						{defender_counts}
					</tr>
					<tr>
						<th>
							{weapon}
						</th>
						{defender_weapons}
					</tr>
					<tr>
						<th>
							{shield}
						</th>
						{defender_shields}
					</tr>
					<tr>
						<th>
							{hull_plating}
						</th>
						{defender_hull_platings}
					</tr>
				</table>
			</center>
		</th>
	</tr>
</table>
{summary}