<?php
/*
  This file is part of WOT Game.

    WOT Game is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    WOT Game is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with WOT Game.  If not, see <http://www.gnu.org/licenses/>.
*/
  //config.php :: Archivo de configuracion
// Este archivo es autogenerado | This files is autogenerated
if(!defined("INSIDE")){ die("attemp hacking");}
	$dbsettings = Array(
		"server"        => "xen251.linea7.net", //MySQL server name. (Default: localhost)
		"user"          => "nngame", // MySQL username.
		"pass"          => "gnomlin", // GundamMySQL password.
		"name"          => "nngame", // MySQL database name.
		"prefix"        => "ugml_", // Prefix for table names.
		"secretword"    => "verysecret"); // Secret word used when hashing information for cookies.
// Created by Perberos. All rights reversed (C) 2006
?>